# This workflows will build, test and upload the package to npm when a release
# is created.
# To create a release, please follow the steps documented in the "Build &
# Publish" section of the README.md file.

name: Upload Package
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  test:
    uses: ./.github/workflows/end-to-end-tests.yml
    secrets: inherit

  build:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
          scope: "@readalongs"
      - run: npm install
      - name: Build and bundle
        run: |
          npx nx build web-component
          npx nx bundle web-component
          npx nx build ngx-web-component
      - name: Check that the web-component bundle was up to date
        run: |
          if git status --porcelain | grep packages/studio-web/src/assets/; then echo ERROR: The web-component bundle is out of date. Please run \"npx nx bundle web-component\" and commit the results, then update the tag and try again.; false; fi
      - name: Check that the versions are in sync
        run: |
          wcver=$(npm view dist/packages/web-component version)
          nwcver=$(npm view dist/packages/ngx-web-component version)
          pdep=$(npm view dist/packages/ngx-web-component peerDependencies.@readalongs/web-component)
          if test "$wcver" != "$nwcver"; then echo ERROR: The ngx-web-component version $nwcver does not match the web-component version $wcver.  Please update packages/web-component/package.json and packages/ngx-web-component/package.json, commit the results, update the tag and try again.; false; fi
          if test "$pdep" != "$wcver"; then echo ERROR: ngx-web-component has a peerDependency on @readalongs/web-component version $pdep, which does not match the web-component version $wcver.  Please update packages/ngx-web-component/package.json, commit the results, update the tag and try again.; false; fi
      - name: Publish web-component to npmjs
        run: |
          cd dist/packages/web-component && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish ngx-web-component to npmjs
        run: |
          cd dist/packages/ngx-web-component && npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ github.token }}
          tag: ${{ github.ref_name }}
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ steps.changelog.outputs.changes }}
